=== api-evangelist/microsoft-azure-active-directory/json-schema/microsoft-graph-identity-user-update-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "UserUpdate",
  "type": "object",
  "description": "Properties that can be updated on an existing user.",
  "properties": {
    "accountEnabled": {
      "type": "boolean"
    },
    "displayName": {
      "type": "string"
    },
    "givenName": {
      "type": "string"
    },
    "surname": {
      "type": "string"
    },
    "jobTitle": {
      "type": "string"
    },
    "department": {
      "type": "string"
    },
    "mail": {
      "type": "string"
    },
    "mobilePhone": {
      "type": "string"
    },
    "businessPhones": {
      "type": "array"
    },
    "city": {
      "type": "string"
    },
    "state": {
      "type": "string"
    },
    "country": {
      "type": "string"
    },
    "postalCode": {
      "type": "string"
    },
    "streetAddress": {
      "type": "string"
    },
    "officeLocation": {
      "type": "string"
    },
    "usageLocation": {
      "type": "string"
    },
    "preferredLanguage": {
      "type": "string"
    },
    "employeeId": {
      "type": "string"
    },
    "employeeType": {
      "type": "string"
    },
    "companyName": {
      "type": "string"
    }
  }
}

=== api-evangelist/microsoft-azure-active-directory/examples/microsoft-graph-identity-user-update-example.json
{
  "accountEnabled": true,
  "displayName": "example_value",
  "givenName": "example_value",
  "surname": "example_value",
  "jobTitle": "example_value",
  "department": "example_value",
  "mail": "example_value",
  "mobilePhone": "example_value",
  "businessPhones": [],
  "city": "example_value",
  "state": "example_value",
  "country": "example_value",
  "postalCode": "example_value",
  "streetAddress": "example_value",
  "officeLocation": "example_value",
  "usageLocation": "example_value",
  "preferredLanguage": "example_value",
  "employeeId": "500123",
  "employeeType": "example_value",
  "companyName": "example_value"
}
